services:
  web:
    # image is built locally from the Dockerfile(s)
    build:
      context: .
      dockerfile: Dockerfile
    ports: # host:container
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    develop:
      watch: # rules from .dockerignore apply
        - action: sync # sync source changes without rebuilding the image
          path: .
          target: /usr/src/app
        - action: rebuild # rebuild image when dependencies change
          path: requirements.txt

  db:
    # image is pulled from Docker Hub
    image: postgres:14
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: passwordhere
      POSTGRES_DB: blog
    ports:
      - "5432:5432" # unnecessary but useful for debugging:
                    # web already has access to the db container through the default bridge network
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask -d blog"] # test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  db-data:
    name: flask-postgres-data
