x-web-service: &default-web-service
  depends_on:
    db:
      condition: service_healthy
      restart: true

services:
  web-dev:
    <<: *default-web-service
    container_name: flask-dev
    profiles: ["dev"]
    # image is built locally from the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # load environment variables from a file
    env_file: ".env"
    # specific environment variables for this service (override the ones from the env_file)
    environment:
      FLASK_DEBUG: "1"
    ports: # host:container
      - "8080:8080"
    develop:
      watch: # rules from .dockerignore apply
        - action: sync # sync source changes without rebuilding the image
          path: .
          target: /usr/src/app
        - action: rebuild # rebuild image when dependencies change
          path: requirements.txt
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080", "--reload"] # overrides CMD from the Dockerfile

  web-prod:
    <<: *default-web-service
    container_name: flask-prod
    profiles: ["prod"]
    # image is pulled from the GitLab Container Registry
    image: "${CI_REGISTRY_IMAGE}:${TAG}"
    restart: unless-stopped
    # load environment variables from a file
    env_file: ".env"
    ports: # host:container
      - "8081:8080"
    # command: CMD from the Dockerfile is used by default
    healthcheck:
    # NB: python:3.11-slim doesn't have curl installed
      test:
        [
          "CMD-SHELL",
          "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8080/', timeout=2)\""
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  db:
    container_name: flask-db
    profiles: ["dev", "prod"]
    # image is pulled from Docker Hub
    image: postgres:14
    restart: unless-stopped
    # load environment variables from a file
    env_file: ".env"
    # ports is unnecessary as the web services already has access to the db container through the default bridge network 
    # and postgres doesn't need to be exposed to the host machine
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  db-data:
    name: flask-postgres-data

# optional: the default network is created automatically if not specified
networks:
  default: # default driver will be 'bridge'
