"""Initial migration

Revision ID: c48e569281f0
Revises: 
Create Date: 2026-08-06 20:21:12.363168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48e569281f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_name', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_views')
    # ### end Alembic commands ###
